### ISSUE TITLE
Timezone doesn't work on linux

### ISSUE THREAD

**Issue by Guillaume-Fortin** [Thetyne/BodyReport#53]
Stack trace
`fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The time zone ID 'Romance Standard Time' was not found on the local computer.
System.TimeZoneNotFoundException: The time zone ID 'Romance Standard Time' was not found on the local computer. ---> System.IO.FileNotFoundException: Could not find file '/usr/share/zoneinfo/Romance Standard Time'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at System.TimeZoneInfo.TryGetTimeZoneByFile(String id, TimeZoneInfo& value, Exception& e)`

**Comment by Guillaume-Fortin** [comment]
Temporary Fix : Take a default time zone without user exception
